# yaml-language-in_grpc: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  generate:
    aliases:
      - gen
    cmds:
      - protoc -I=api/proto api/proto/*.proto --go_out=api/gen --go_opt=paths=source_relative --go-grpc_out=api/gen --go-grpc_opt=paths=source_relative
  up:
    cmds:
      - docker-compose up
  build:
    cmds:
      - docker-compose build
  build-up:
    cmds:
      - docker-compose up --build
  test:
    cmds:
      - go test ./... {{.CLI_ARGS}}
  push:
    vars:
      MSG: '{{default "fix" .CLI_ARGS}}'
    cmds:
      - git add .
      - git commit -m "{{.MSG}}"
      - git push -u origin main
  swag:
    cmds:
      - swag init -g ./services/gateway/cmd/main.go -o ./docs --parseDependency --parseInternal
  pull:
    cmds:
      - docker pull alpine/flake8:latest
      - docker pull python:3.11-alpine