// Code generated by "stringer -type=Language"; DO NOT EDIT.

package lang

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Python-0]
	_ = x[Go-1]
	_ = x[C-2]
	_ = x[Cpp-3]
}

const _Language_name = "PythonGoCCpp"

var _Language_index = [...]uint8{0, 6, 8, 9, 12}

func (i Language) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Language_index)-1 {
		return "Language(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Language_name[_Language_index[idx]:_Language_index[idx+1]]
}
