// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/rest/analyze": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analyze"
                ],
                "summary": "Code analyzing",
                "parameters": [
                    {
                        "description": "Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services_gateway_internal_transport_rest.AnalyzeRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/lingva_pkg_rest.Response-lingva_api_gen_AnalyzeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/lingva_pkg_rest.Response-any"
                        }
                    }
                }
            }
        },
        "/ws/run": {
            "get": {
                "description": "Connect to websocket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "run"
                ],
                "summary": "Run code",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_internal_transport_websocket.WSResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services_gateway_internal_transport_websocket.WSResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "lingva_api_gen.AnalyzeResponse": {
            "type": "object",
            "properties": {
                "diagnostics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/lingva_api_gen.Diagnostic"
                    }
                }
            }
        },
        "lingva_api_gen.Diagnostic": {
            "type": "object",
            "properties": {
                "column": {
                    "type": "integer"
                },
                "line": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "severity": {
                    "$ref": "#/definitions/lingva_api_gen.Severity"
                }
            }
        },
        "lingva_api_gen.Severity": {
            "type": "integer",
            "format": "int32",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-varnames": [
                "Severity_ERROR",
                "Severity_WARNING",
                "Severity_INFO"
            ]
        },
        "lingva_pkg_rest.Response-any": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "lingva_pkg_rest.Response-lingva_api_gen_AnalyzeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/lingva_api_gen.AnalyzeResponse"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "services_gateway_internal_transport_rest.AnalyzeRequestDTO": {
            "type": "object",
            "required": [
                "Code",
                "Lang"
            ],
            "properties": {
                "Code": {
                    "type": "string"
                },
                "Lang": {
                    "type": "string"
                }
            }
        },
        "services_gateway_internal_transport_websocket.WSResponse": {
            "type": "object",
            "properties": {
                "is_finished": {
                    "type": "boolean"
                },
                "stderr": {
                    "type": "string"
                },
                "stdout": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Lingva Gateway API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
