name: Test

on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Pull Docker Images
        run: |
          docker pull alpine/flake8:latest
          docker pull python:3.11-alpine

      - name: Lint Code
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

      - name: Run Tests
        run: go test -v ./...